### ISSUE TITLE
Detach doesn't seem to work

### ISSUE THREAD

**Issue by shreyasborole** [JumbomanXDA/YouTube-vanced-Magisk-Module#4]
Detach script doesn't seem to work, my Vanced app has been updated to Play Store's YouTube app. This is recurring problem even in a different ROM.

OS: Android 12
Device: Realme 6
Magisk: v24.1

**Comment by JumbomanXDA** [comment]
Can you try 24th feb build
Clean flash recommend

**Comment by ARitz-Cracker** [comment]
Where's this build? There are no commits in this repo since January and there isn't anything in releases

**Comment by JumbomanXDA** [comment]
> Where's this build? There are no commits in this repo since January and there isn't anything in releases

http://t.me/Unofficial_YouTube_Vanced_Module

**Comment by shreyasborole** [comment]
> Can you try 24th feb build Clean flash recommend

I have updated it, Vanced doesn't seem to update to Play Store's Youtube (as of now). Will keep you updated.

**Comment by shreyasborole** [comment]
It seems the latest version on Telegram works like a charm! Thanks
