### ISSUE TITLE
Uninstall after first reboot

### ISSUE THREAD

**Issue by jashoewa** [JumbomanXDA/YouTube-vanced-Magisk-Module#5]
After installing the module, Vanced works but gets uninstalled after rebooting. I took a look at the magisk folder and found the uninstall script in service.d, while looking at the code for that script it looks for the vanced module folder in /data/adb/modules but your module actually gets installed to /data/adb/modules_update until the next reboot. Since it can't find the vanced folder in the modules directory yet, since it wasn't moved there, it uninstalls.

**Comment by JumbomanXDA** [comment]
Can you share the magisk log on telegram t.me/JumbomanXDA
Steps
1. Flash module
2. Reboot the device
3. Share the log. Go to magisk app > logs tab
